version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: garden
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gardendb
    ports:
      - "5431:5432"
    volumes:
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker-entrypoint-initdb.d/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  postgres-data: